### ISSUE TITLE
popView is actually a new view?

### ISSUE THREAD

**Issue by jaypeeZero** [pwalczyszyn/backstack#12]
When I do pushView, then on that new view I do popView, the old view does not have the data that was previously assigned to it.

For example in View1 during Init I populate "this.model" and use it during "this.render".  It works fine when I come in with pushView (and pass in options).
When I do popView from View2, suddenly View1 doesn't have any "this.options" and "this.model" cannot be set properly.

This feels like a bug as I won't always have access to the information I need when I am doing a popView….since I am only trying to go Back.

**Comment by pwalczyszyn** [comment]
Try adding destructionPolicy:'never' property to your Backbone view.

**Comment by jaypeeZero** [comment]
Ok, that did fix the issue, but I can't seem to find good documentation on "destructionPolicy" so I'm assuming this is to do with BackStack and not to do with Backbone.js?  
What are the implications of that setting?

**Comment by jaypeeZero** [comment]
It seems like destructionPolicy:'never' keeps both the Init and Render events from firing.  This doesn't feel like proper functionality.  I would assume that if I told the view never to destroy that Init wouldn't fire again, but Render should.  
Otherwise it will be difficult to cause the View to change visually based on the 2nd View changing data.  
For example, View1 is a list of things, View2 adds a new thing and calls "popView".  Without Render firing, I can't update View1's list with the updated information.
