### ISSUE TITLE
Is there a way how to use Backpack with sidebar-body layout?

### ISSUE THREAD

**Issue by dmarko484** [pwalczyszyn/backstack#9]
Is there a way how to use Backpack with sidebar-body layout? I mean traditional ipad layout with independent sidebar and body part? If so, can you share some example?

**Comment by pwalczyszyn** [comment]
You can have multiple BackStack instances in one app. You can checkout a demo app here: http://pwalczyszyn.github.com/backstack which has a top bar as independent component.
